-- E-commerce schema (post-pivot 2026-04-26)
-- 7 tables : products, customers, orders, order_items, shipments, events, targets, calendar_events
-- All tables RLS enabled, SELECT-only for authenticated role.

-- ======================
-- products
-- ======================
create table public.products (
  id uuid primary key default gen_random_uuid(),
  sku text not null unique,
  name text not null,
  category text not null check (category in ('apparel','home','beauty','tech','accessories')),
  segment text not null check (segment in ('basic','standard','premium')),
  price_cents integer not null check (price_cents >= 0),
  status text not null check (status in ('active','draft','sold_out')),
  stock integer not null check (stock >= 0),
  rating numeric(2,1) not null check (rating between 0 and 5),
  created_at timestamptz not null default now()
);

create index products_status_idx on public.products(status);
create index products_category_idx on public.products(category);
create index products_created_at_idx on public.products(created_at desc);

-- ======================
-- customers
-- ======================
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  full_name text not null,
  country text not null,
  segment text not null check (segment in ('basic','standard','premium')),
  created_at timestamptz not null default now()
);

create index customers_country_idx on public.customers(country);
create index customers_segment_idx on public.customers(segment);

-- ======================
-- orders
-- ======================
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  status text not null check (status in ('paid','pending','refunded','canceled')),
  total_cents integer not null check (total_cents >= 0),
  channel text not null check (channel in ('online','store')),
  created_at timestamptz not null default now(),
  paid_at timestamptz null,
  constraint orders_paid_at_consistency check (
    (status = 'paid' and paid_at is not null) or (status <> 'paid')
  )
);

create index orders_status_created_at_idx on public.orders(status, created_at desc);
create index orders_paid_at_idx on public.orders(paid_at desc) where paid_at is not null;
create index orders_channel_idx on public.orders(channel);
create index orders_customer_id_idx on public.orders(customer_id);

-- ======================
-- order_items
-- ======================
create table public.order_items (
  id bigint primary key generated by default as identity,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0)
);

create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_product_id_idx on public.order_items(product_id);

-- ======================
-- shipments
-- ======================
create table public.shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  hub text not null check (hub in ('paris','lyon','marseille','bordeaux','lille','strasbourg')),
  status text not null check (status in ('in_transit','delivered','returned')),
  shipped_at timestamptz not null,
  delivered_at timestamptz null,
  constraint shipments_delivered_at_consistency check (
    (status = 'delivered' and delivered_at is not null) or (status <> 'delivered')
  )
);

create index shipments_status_idx on public.shipments(status);
create index shipments_hub_idx on public.shipments(hub);

-- ======================
-- events
-- ======================
create table public.events (
  id bigint primary key generated by default as identity,
  customer_id uuid null references public.customers(id) on delete set null,
  type text not null check (type in ('visit','add_to_cart','checkout','paid','login','signup')),
  occurred_at timestamptz not null default now(),
  metadata jsonb null
);

create index events_type_occurred_at_idx on public.events(type, occurred_at desc);
create index events_customer_id_idx on public.events(customer_id);

-- ======================
-- targets (objectifs mensuels)
-- ======================
create table public.targets (
  month date primary key,
  revenue_cents bigint not null check (revenue_cents >= 0)
);

-- ======================
-- calendar_events (campagnes UI W13)
-- ======================
create table public.calendar_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  tag text not null check (tag in ('campagne','marketing','stock','email')),
  starts_at timestamptz not null,
  duration_min integer not null default 60 check (duration_min > 0)
);

create index calendar_events_starts_at_idx on public.calendar_events(starts_at);

-- ======================
-- RLS : SELECT-only for authenticated, no INSERT/UPDATE/DELETE policies
-- ======================
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.shipments enable row level security;
alter table public.events enable row level security;
alter table public.targets enable row level security;
alter table public.calendar_events enable row level security;

create policy products_select_authenticated on public.products
  for select to authenticated using (true);
create policy customers_select_authenticated on public.customers
  for select to authenticated using (true);
create policy orders_select_authenticated on public.orders
  for select to authenticated using (true);
create policy order_items_select_authenticated on public.order_items
  for select to authenticated using (true);
create policy shipments_select_authenticated on public.shipments
  for select to authenticated using (true);
create policy events_select_authenticated on public.events
  for select to authenticated using (true);
create policy targets_select_authenticated on public.targets
  for select to authenticated using (true);
create policy calendar_events_select_authenticated on public.calendar_events
  for select to authenticated using (true);
