-- Schema initial : users, subscriptions, events + RLS
create extension if not exists pgcrypto;

create table public.users (
  id          uuid primary key default gen_random_uuid(),
  email       text not null unique,
  full_name   text not null,
  country     text not null,
  created_at  timestamptz not null default now()
);

create table public.subscriptions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null unique references public.users(id) on delete cascade,
  plan         text not null check (plan in ('free','pro','enterprise')),
  mrr_cents    integer not null check (mrr_cents >= 0),
  status       text not null check (status in ('active','canceled')),
  started_at   timestamptz not null,
  canceled_at  timestamptz,
  constraint subscriptions_canceled_at_consistency
    check ((status = 'canceled' and canceled_at is not null and canceled_at >= started_at)
        or (status = 'active'   and canceled_at is null))
);

create table public.events (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.users(id) on delete cascade,
  type         text not null check (type in ('signup','login','feature_use')),
  occurred_at  timestamptz not null
);

create index events_user_id_occurred_at_idx        on public.events (user_id, occurred_at);
create index events_type_occurred_at_idx           on public.events (type, occurred_at);
create index users_created_at_desc_idx             on public.users (created_at desc);
create index subscriptions_status_canceled_at_idx  on public.subscriptions (status, canceled_at);
create index subscriptions_started_at_idx          on public.subscriptions (started_at);

-- RLS : SELECT autorisé aux authentifiés, aucune écriture côté client
alter table public.users         enable row level security;
alter table public.subscriptions enable row level security;
alter table public.events        enable row level security;

create policy "users_select_authenticated"
  on public.users for select
  to authenticated
  using (true);

create policy "subscriptions_select_authenticated"
  on public.subscriptions for select
  to authenticated
  using (true);

create policy "events_select_authenticated"
  on public.events for select
  to authenticated
  using (true);
